set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(TARGET_TRIPLE riscv64-unknown-linux-gnu)
set(RISCV_GCC_BUILD_ROOT /usr/bin)

set(CMAKE_C_COMPILER ${RISCV_GCC_BUILD_ROOT}/riscv64-linux-gnu-gcc)
set(CMAKE_C_COMPILER_TARGET ${TARGET_TRIPLE})
set(CMAKE_CXX_COMPILER ${RISCV_GCC_BUILD_ROOT}/riscv64-linux-gnu-g++)
set(CMAKE_CXX_COMPILER_TARGET ${TARGET_TRIPLE})
set(CMAKE_ASM_COMPILER ${RISCV_GCC_BUILD_ROOT}/riscv64-linux-gnu-as)
set(CMAKE_ASM_COMPILER_TARGET ${TARGET_TRIPLE})

# Don't run the linker on compiler check
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
